name: Pull Request

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
        cache: 'yarn'
    - name: Set env to dev
      shell: bash
      run: |
        touch .env
        echo "VITE_APP_ENVIRONMENT=dev" >> .env
        echo "VITE_APP_VERSION=$npm_package_version" >> .env
    - name: Install Dependencies
      shell: bash
      run: yarn install --immutable