name: Lighthouse Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Set env to cypress
        run: |
          touch .env
          echo "VITE_APP_ENVIRONMENT=dev" >> .env
          echo "VITE_APP_VERSION=$npm_package_version" >> .env
      - name: Restore Yarn cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - run: yarn build
      - run: yarn preview & npx wait-on http://localhost:3000
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: 'http://localhost:3000'
          wptConnectionSpeed: threegfast