name: Lighthouse Tests
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - name: Install Dependencies
        run: yarn install --immutable
      - run: yarn build
      - run: yarn serve & npx wait-on http://localhost:3000
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: 'http://localhost:3000'
          wptConnectionSpeed: threegfast