name: Lighthouse Tests
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.1'
      - uses: pnpm/action-setup@v2
      - name: Set env to cypress
        run: |
          touch .env
          echo "VITE_APP_ENVIRONMENT=dev" >> .env
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm build
      - run: pnpm serve & npx wait-on http://localhost:3000
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: 'http://localhost:3000'
          wptConnectionSpeed: threegfast