name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests, Linting, Bundle Size Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint:nowarn
      - name: Run Unit Tests
        run: yarn coverage
      - name: Build the app
        run: yarn build
      - name: Bundlesize Check
        run: yarn bundlesize
      - uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: ./coverage/example.lcov
          min_coverage: 90
          token: ${{ github.token }}
